theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
idle-timeout = 100
completion-trigger-len = 1
gutters = ["diagnostics", "line-numbers", "diff", "spacer"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "diagnostics", "spinner"]
center = ["file-name"]
right = ["selections", "position", "version-control", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.file-picker]
hidden = false
ignore = false

[editor.search]
smart-case = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will looiik like "→···" (depending on tab width)

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
# change basic behavior
"esc" = ["collapse_selection", "keep_primary_selection"]
"a" = ["append_mode", "collapse_selection"]
"i" = ["insert_mode", "collapse_selection"]
"y" = ["yank_joined_to_clipboard"]
"p" = ["paste_clipboard_after"]
"P" = ["paste_clipboard_before"]
"R" = ["replace_selections_with_clipboard"]

# move line up & down
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# shortcut for jumping buffer
"L" = "goto_next_buffer"
"H" = "goto_previous_buffer"
# shortcut for jumping window
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"'" = "repeat_last_motion"
"X" = "extend_line_above"
"C-s" = ":w"

[keys.normal.space]
"l" = {"f" = ":format"}
"q" = ":bc"
"y" = ["yank"]
"p" = ["paste_after"]
"P" = ["paste_before"]
"R" = ["replace_with_yanked"]

[keys.select]
# change basic behavior
"y" = ["yank_joined_to_clipboard"]
# move line up & down
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
X = "extend_line_above"
"R" = ["replace_selections_with_clipboard"]

[keys.select.space]
"y" = ["yank"]

