# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html

[language-server]
pyright = { command = "pyright-langserver", args = ["--stdio"], config = {} }
prettier = { command = 'prettier', args = ["--parser", "typescript"] }
ltex-ls = { command = "ltex-ls", config = {} }


[[language]]
name = "toml"
language-servers = []


[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
roots = [".marksman.toml"]
language-servers = ["marksman", "ltex-ls"]
indent = { tab-width = 2, unit = "  " }


[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = ["pyproject.toml"]
comment-token = "#"
language-servers = [ { name = "pyright", except-features = ["format"] }]
formatter = { command = "black", args = ["--quiet", "-"] }
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "(js|javascript)"
language-id = "javascript"
file-types = ["js", "mjs", "cjs"]
shebangs = ["node"]
roots = []
comment-token = "//"
language-servers = [ "typescript-language-server" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
indent = { tab-width = 2, unit = "  " }


[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
language-id = "typescript"
shebangs = []
roots = []
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "prettier" ]
indent = { tab-width = 2, unit = "  " }

