# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html

[language-server]
vscode-json-language-server =  { command = "vscode-json-language-server", args = ["--stdio"], config = { provideFormatter = true } }
prettier = { command = 'prettier', args = ["--parser", "typescript"] }
ltex-ls = { command = "ltex-ls", config = {} }
pyright = { command = "pyright-langserver", args = ["--stdio"], config = {} }
# ruff-lsp = { command = "ruff-lsp", config = { settings = { args = [] } } }

# due to this issue https://github.com/helix-editor/helix/issues/5174#issuecomment-1353668616
[[language]]
name = "toml"
language-servers = []

[[language]]
name = "json"
scope = "source.json"
injection-regex = "json"
file-types = ["json", "jsonc", "arb", "ipynb", "geojson"]
roots = []
language-servers = [ "vscode-json-language-server" ]
auto-format = false
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
roots = [".marksman.toml"]
language-servers = ["marksman", "ltex-ls"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = ["pyproject.toml"]
comment-token = "#"
# language-servers = [ { name = "ruff-lsp" }]
language-servers = [ { name = "pyright", except-features = ["format"] }]
formatter = { command = "black", args = ["--quiet", "-"] }
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "(js|javascript)"
language-id = "javascript"
file-types = ["js", "mjs", "cjs"]
shebangs = ["node"]
roots = []
comment-token = "//"
language-servers = [ "typescript-language-server" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
indent = { tab-width = 2, unit = "  " }


[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
language-id = "typescript"
shebangs = []
roots = []
# language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "prettier" ]
language-servers = [ "typescript-language-server" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
indent = { tab-width = 2, unit = "  " }

